[project]
name = "flatmapknowledge"
version = "2.7.0"
description = ""
authors = [
    { name = "David Brooks", email = "d.brooks@auckland.ac.nz"},
]
requires-python = "==3.12.*"
dependencies = [
    "mapknowledge",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.uv.sources]
mapknowledge = { url = "https://github.com/napakalas/map-knowledge/releases/download/mapknowledge-2026-03-02/mapknowledge-1.5.0-py3-none-any.whl" }
